// Automatically generated by astro-icon
// 2486d9613dff14885bc9044a6be36377f504f767ae4195407772cf96f23ab882

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "creator"
		| "remaining"
		| "server"
		| "updated";
}